-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 20:33:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `idSexo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'Masculino ou feminino ou outros',
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridade` (
  `idEscolaridade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_civil` (
  `idEstado_civil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_fisica` (
  `Pessoa_idPessoa` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  `Escolaridade_idEscolaridade` INT NULL,
  `data_nasc` DATE NOT NULL,
  `fornecedor` BIT(1) NOT NULL,
  `Estado_civil_idEstado_civil` INT NOT NULL,
  `email` TEXT NULL,
  `identidade` VARCHAR(7) NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  INDEX `fk_Pessoa_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Pessoa_fisica_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Pessoa_fisica_Escolaridade1_idx` (`Escolaridade_idEscolaridade` ASC) VISIBLE,
  INDEX `fk_Pessoa_fisica_Estado_civil1_idx` (`Estado_civil_idEstado_civil` ASC) VISIBLE,
  INDEX `fk_Pessoa_fisica_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `mydb`.`Sexo` (`idSexo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_fisica_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_fisica_Escolaridade1`
    FOREIGN KEY (`Escolaridade_idEscolaridade`)
    REFERENCES `mydb`.`Escolaridade` (`idEscolaridade`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_fisica_Estado_civil1`
    FOREIGN KEY (`Estado_civil_idEstado_civil`)
    REFERENCES `mydb`.`Estado_civil` (`idEstado_civil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_fisica_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`idSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `salario` FLOAT NOT NULL,
  `Setor_idSetor` INT NOT NULL,
  PRIMARY KEY (`idCargo`),
  INDEX `fk_Cargo_Setor1_idx` (`Setor_idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `mydb`.`Setor` (`idSetor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_telefone` (
  `idTipo_Telefone` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'residencial, pessoal',
  PRIMARY KEY (`idTipo_Telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` TEXT NOT NULL,
  `Tipo_telefone_idTipo_Telefone` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Tipo_telefone1_idx` (`Tipo_telefone_idTipo_Telefone` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Tipo_telefone1`
    FOREIGN KEY (`Tipo_telefone_idTipo_Telefone`)
    REFERENCES `mydb`.`Tipo_telefone` (`idTipo_Telefone`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_endereco` (
  `idTipo_endereco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idBairro`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` TEXT NOT NULL,
  `numero` TEXT NOT NULL,
  `cep` TEXT NOT NULL,
  `complemento` TEXT NULL,
  `Tipo_endereco_idTipo_endereco` INT NOT NULL,
  `Bairro_idBairro` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Tipo_endereco1_idx` (`Tipo_endereco_idTipo_endereco` ASC) VISIBLE,
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Tipo_endereco1`
    FOREIGN KEY (`Tipo_endereco_idTipo_endereco`)
    REFERENCES `mydb`.`Tipo_endereco` (`idTipo_endereco`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `mydb`.`Bairro` (`idBairro`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desconto` (
  `idDesconto` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`idDesconto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `comissao` FLOAT NULL,
  `nome_pai` TEXT NULL,
  `data_nasc_pai` DATE NULL,
  `nome_mae` TEXT NOT NULL,
  `data_nasc_mae` DATE NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NULL,
  `ativo` BIT(1) NOT NULL,
  PRIMARY KEY (`Pessoa_fisica_Pessoa_idPessoa`),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Funcionario_Pessoa_fisica1_idx` (`Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Funcionario_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_Pessoa_fisica1`
    FOREIGN KEY (`Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_fisica` (`Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_mercadoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_mercadoria` (
  `idTipo_mercadoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Desconto_idDesconto` INT NULL,
  PRIMARY KEY (`idTipo_mercadoria`),
  INDEX `fk_Tipo_mercadoria_Desconto1_idx` (`Desconto_idDesconto` ASC) VISIBLE,
  CONSTRAINT `fk_Tipo_mercadoria_Desconto1`
    FOREIGN KEY (`Desconto_idDesconto`)
    REFERENCES `mydb`.`Desconto` (`idDesconto`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_juridica` (
  `Pessoa_idPessoa` INT NOT NULL,
  `cnpj` INT NOT NULL,
  `fornecedor` BIT(1) NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  INDEX `fk_Pessoa_juridica_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Pessoa_juridica_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_juridica_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_juridica_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `Desconto_idDesconto` INT NULL,
  `Pessoa_juridica_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Desconto1_idx` (`Desconto_idDesconto` ASC) VISIBLE,
  INDEX `fk_Marca_Pessoa_juridica1_idx` (`Pessoa_juridica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Desconto1`
    FOREIGN KEY (`Desconto_idDesconto`)
    REFERENCES `mydb`.`Desconto` (`idDesconto`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Marca_Pessoa_juridica1`
    FOREIGN KEY (`Pessoa_juridica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_juridica` (`Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mercadoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mercadoria` (
  `idMercadoria` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `preco_venda` FLOAT NOT NULL,
  `peso` VARCHAR(10) NULL,
  `quantidade` INT NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `volume` VARCHAR(10) NULL,
  `criado_em` TIMESTAMP NOT NULL,
  `preco_compra` FLOAT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `Tipo_mercadoria_idTipo_mercadoria` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Mercadoria_Desconto` INT NULL,
  PRIMARY KEY (`idMercadoria`),
  INDEX `fk_Mercadoria_Desconto1_idx` (`Mercadoria_Desconto` ASC) VISIBLE,
  INDEX `fk_Mercadoria_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Mercadoria_Tipo_mercadoria1_idx` (`Tipo_mercadoria_idTipo_mercadoria` ASC) VISIBLE,
  INDEX `fk_Mercadoria_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Mercadoria_Desconto1`
    FOREIGN KEY (`Mercadoria_Desconto`)
    REFERENCES `mydb`.`Desconto` (`idDesconto`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercadoria_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercadoria_Tipo_mercadoria1`
    FOREIGN KEY (`Tipo_mercadoria_idTipo_mercadoria`)
    REFERENCES `mydb`.`Tipo_mercadoria` (`idTipo_mercadoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercadoria_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Pessoa_fisica_Pessoa_idPessoa`),
  INDEX `fk_Cliente_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pessoa_fisica1`
    FOREIGN KEY (`Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_fisica` (`Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Pessoa_fisica_Pessoa_idPessoa`),
  INDEX `fk_Dependente_Pessoa_fisica1_idx` (`Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Dependente_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Dependente_Pessoa_fisica1`
    FOREIGN KEY (`Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_fisica` (`Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Dependente_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atualizado_em`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atualizado_em` (
  `idAtualizado_em` INT NOT NULL AUTO_INCREMENT,
  `Mercadoria_idMercadoria` INT NOT NULL,
  `instante` TIMESTAMP NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idAtualizado_em`),
  INDEX `fk_Atualizado_em_Mercadoria1_idx` (`Mercadoria_idMercadoria` ASC) VISIBLE,
  INDEX `fk_Atualizado_em_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Atualizado_em_Mercadoria1`
    FOREIGN KEY (`Mercadoria_idMercadoria`)
    REFERENCES `mydb`.`Mercadoria` (`idMercadoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Atualizado_em_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_pagamento` (
  `idTipo_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'À vista, parcelado',
  PRIMARY KEY (`idTipo_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `Desconto_idDesconto` INT NOT NULL,
  `Tipo_pagamento_idTipo_pagamento` INT NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `valor_recebido` FLOAT NOT NULL,
  `troco` FLOAT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_Desconto1_idx` (`Desconto_idDesconto` ASC) VISIBLE,
  INDEX `fk_Pagamento_Tipo_pagamento1_idx` (`Tipo_pagamento_idTipo_pagamento` ASC) VISIBLE,
  INDEX `fk_Pagamento_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Desconto1`
    FOREIGN KEY (`Desconto_idDesconto`)
    REFERENCES `mydb`.`Desconto` (`idDesconto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pagamento_Tipo_pagamento1`
    FOREIGN KEY (`Tipo_pagamento_idTipo_pagamento`)
    REFERENCES `mydb`.`Tipo_pagamento` (`idTipo_pagamento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pagamento_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Cliente_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `Mercadoria_idMercadoria` INT NOT NULL,
  PRIMARY KEY (`Cliente_Pessoa_fisica_Pessoa_idPessoa`, `Pagamento_idPagamento`, `Mercadoria_idMercadoria`),
  INDEX `fk_Compra_Cliente1_idx` (`Cliente_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Compra_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  INDEX `fk_Compra_Mercadoria1_idx` (`Mercadoria_idMercadoria` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Cliente1`
    FOREIGN KEY (`Cliente_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Cliente` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Compra_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Compra_Mercadoria1`
    FOREIGN KEY (`Mercadoria_idMercadoria`)
    REFERENCES `mydb`.`Mercadoria` (`idMercadoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parcela` (
  `idParcela` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `paga` BIT(1) NULL,
  `multa` FLOAT NULL,
  `data_vencimento` DATE NOT NULL,
  `juros` FLOAT NULL,
  `data_pagamento` DATE NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idParcela`),
  INDEX `fk_Parcela_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Parcela_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma_pagamento` (
  `idForma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'cartao de debito - a vista, cartao de credito - parcelado, cheque - a vista, cheque - parcelado, dinheiro - a vista',
  `Tipo_pagamento_idTipo_pagamento` INT NOT NULL,
  PRIMARY KEY (`idForma_pagamento`),
  INDEX `fk_Forma_pagamento_Tipo_pagamento1_idx` (`Tipo_pagamento_idTipo_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Forma_pagamento_Tipo_pagamento1`
    FOREIGN KEY (`Tipo_pagamento_idTipo_pagamento`)
    REFERENCES `mydb`.`Tipo_pagamento` (`idTipo_pagamento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reabastecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reabastecimento` (
  `Mercadoria_idMercadoria` INT NOT NULL,
  `Funcionario_Pessoa_fisica_Pessoa_idPessoa` INT NOT NULL,
  `Pessoa_fisica_Pessoa_idPessoa` INT NULL,
  `Pessoa_juridica_Pessoa_idPessoa` INT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`Mercadoria_idMercadoria`, `Funcionario_Pessoa_fisica_Pessoa_idPessoa`),
  INDEX `fk_Pessoa_juridica_has_Mercadoria_Mercadoria1_idx` (`Mercadoria_idMercadoria` ASC) VISIBLE,
  INDEX `fk_Pessoa_juridica_has_Mercadoria_Pessoa_juridica1_idx` (`Pessoa_juridica_Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Reabastecimento_Pessoa_fisica1_idx` (`Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Reabastecimento_Funcionario1_idx` (`Funcionario_Pessoa_fisica_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_juridica_has_Mercadoria_Pessoa_juridica1`
    FOREIGN KEY (`Pessoa_juridica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_juridica` (`Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_juridica_has_Mercadoria_Mercadoria1`
    FOREIGN KEY (`Mercadoria_idMercadoria`)
    REFERENCES `mydb`.`Mercadoria` (`idMercadoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reabastecimento_Pessoa_fisica1`
    FOREIGN KEY (`Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa_fisica` (`Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reabastecimento_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_fisica_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_fisica_Pessoa_idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone_tem_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone_tem_Pessoa` (
  `Telefone_idTelefone` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Telefone_idTelefone`, `Pessoa_idPessoa`),
  INDEX `fk_Telefone_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Telefone_has_Pessoa_Telefone1_idx` (`Telefone_idTelefone` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_has_Pessoa_Telefone1`
    FOREIGN KEY (`Telefone_idTelefone`)
    REFERENCES `mydb`.`Telefone` (`idTelefone`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_tem_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_tem_endereco` (
  `Endereco_idEndereco` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Endereco_idEndereco`, `Pessoa_idPessoa`),
  INDEX `fk_Endereco_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Endereco_has_Pessoa_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_has_Pessoa_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Endereco_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
